### ISSUE TITLE
Add useful VSC packages to the list so I can implement them into the install script

### ISSUE THREAD

**Issue by vincentaudebert** [springload/dotfiles#12]
@claireynz @thibaudcolas Thanks

Into TO BE IMPLEMENTED section please
https://github.com/springload/dotfiles/blob/feature/shell-script-vsc/config/visual-studio-code/README.md

**Comment by cecenz** [comment]
@vincentaudebert Here are the packages I have found useful :) Mostly stolen from @thibaudcolas 

Zignd.html-css-class-completion
abusaidm.html-snippets
christian-kohler.path-intellisense
mohsen1.prettify-json <- this one is good for KB dashboard!!!!
robinbentley.sass-indented
mrmlnc.vscode-scss
cssho.vscode-svgviewer
jkjustjoshing.vscode-text-pastry
bogdan-sinitsa.theme-dark-monokai <- this is the monokai theme we have currently for sublime dotfiles

**Comment by vincentaudebert** [comment]
Fanta @cecenz ! I just nuked vscode-text-pastry as it just code natively implemented in 1.13 👍 

I'll merge branch to master now 🎉
